### ISSUE TITLE
(epic) User verification

### ISSUE THREAD

**Issue by XertroV** [voteflux/THE-APP#38]
We need a way to verify users sometime soon.
We can do this via an oauth connection to the Flux backend.
We can send stuff like whether their details are valid (and when they were validated last) via oauth scopes.

This thread is for talking about the practicality / implementation / go-ahead-status of this idea.

Implementations required:

- [ ] Add oauth2 resource provider to Flux backend
- [ ] Add a client app (digipol) to dev and prod backends
- [ ] Add oauth2 handshake stuff to digipol app
